<a href="https://colab.research.google.com/github/pishere/neuralNet/blob/master/neuralPractice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount("/content/gdrive")

Mounted at /content/gdrive


In [140]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [0]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
% matplotlib inline
import seaborn as sns

df_orig = pd.read_csv("/content/drive/My Drive/datasets/heart.csv")

In [0]:
df = df_orig.copy()

In [0]:
df.fillna(df.mean(),inplace=True)

In [253]:
df.isna().sum()
df.shape

(4238, 16)

In [0]:
df_train = df.head(3038)
df_test = df.tail(1200)

In [0]:
X = df_train[["male", "age", "education", "currentSmoker", "cigsPerDay", "BPMeds", "prevalentStroke", "prevalentHyp", "diabetes", "totChol", "sysBP", "diaBP", "BMI", "heartRate", "glucose"]]
y = df_train[["TenYearCHD"]]

In [256]:
X.describe()

male          age  ...    heartRate      glucose
count  3038.000000  3038.000000  ...  3038.000000  3038.000000
mean      0.423963    49.550033  ...    75.544397    81.827702
std       0.494266     8.577637  ...    11.864305    21.669990
min       0.000000    32.000000  ...    44.000000    40.000000
25%       0.000000    42.000000  ...    68.000000    72.000000
50%       0.000000    49.000000  ...    75.000000    80.000000
75%       1.000000    56.000000  ...    82.000000    85.000000
max       1.000000    70.000000  ...   140.000000   394.000000

[8 rows x 15 columns]

In [257]:
y.head()

TenYearCHD
0           0
1           0
2           0
3           1
4           0

In [258]:
X.isna().sum()

male               0
age                0
education          0
currentSmoker      0
cigsPerDay         0
BPMeds             0
prevalentStroke    0
prevalentHyp       0
diabetes           0
totChol            0
sysBP              0
diaBP              0
BMI                0
heartRate          0
glucose            0
dtype: int64

In [0]:
from sklearn import preprocessing

x = X #returns a numpy array
min_max_scaler = preprocessing.MinMaxScaler()
x_scaled = min_max_scaler.fit_transform(x)
X = pd.DataFrame(x_scaled)

In [260]:
X.describe()

0            1   ...           13           14
count  3038.000000  3038.000000  ...  3038.000000  3038.000000
mean      0.423963     0.461843  ...     0.328587     0.118157
std       0.494266     0.225727  ...     0.123587     0.061215
min       0.000000     0.000000  ...     0.000000     0.000000
25%       0.000000     0.263158  ...     0.250000     0.090395
50%       0.000000     0.447368  ...     0.322917     0.112994
75%       1.000000     0.631579  ...     0.395833     0.127119
max       1.000000     1.000000  ...     1.000000     1.000000

[8 rows x 15 columns]

In [0]:
X = X.to_numpy()

In [0]:
X = X.transpose()

In [263]:
print(X)
print(X.shape)

[[1.         0.         1.         ... 1.         0.         1.        ]
 [0.18421053 0.36842105 0.42105263 ... 0.55263158 0.05263158 0.15789474]
 [1.         0.33333333 0.         ... 1.         0.33333333 1.        ]
 ...
 [0.27702375 0.31968008 0.23751818 ... 0.2668444  0.22903539 0.34464372]
 [0.375      0.53125    0.32291667 ... 0.10416667 0.58333333 0.63541667]
 [0.10451977 0.10169492 0.08474576 ... 0.09322034 0.09039548 0.06497175]]
(15, 3038)


In [0]:
y = y.to_numpy()
y = y.transpose()

In [265]:
print(y)
print(y.shape)

[[0 0 0 ... 0 0 0]]
(1, 3038)


In [0]:
w = np.ones((15,1))

In [267]:
print(w)
print(w.shape)
b = 0

[[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]]
(15, 1)


In [0]:
def sigma(z):
    1/(1+np.exp(-z))

In [0]:
def gradient_descent(X, y, w, b, lr = 0.001):
    m = y.shape[1]

    # FORWARD PROPAGATION (FROM X TO COST)
    Z = np.matmul(w.T, X) + b    
    A = sigma(Z)  
    cost = -1/m*np.sum(y*np.log(A)+(1-y)*np.log(1-A))   
    
    # BACKWARD PROPAGATION (TO FIND GRAD)                               
    dz = A - y                                     # A = [yhat1, yhat2, ...],  # rate of change of J wrt z
    db = (1/m) * np.sum(dz)
    dw = (1/m) * np.matmul(X , dz.T)

    w = w - lr*dw
    b = b - lr*dw

    cost = np.squeeze(cost)

    grads = {"dw": dw,
             "db": db}
    
    return grads, cost

In [270]:
grad,cost = gradient_descent(X, y, w, b)

TypeError: ignored

In [206]:
print ("dw = " + str(grad["dw"]))
print ("db = " + str(grad["db"]))
print ("cost = " + str(cost))

dw = [[3.44634628e-01]
 [4.13321264e+01]
 [1.69933826e+00]
 [4.13100724e-01]
 [7.33378849e+00]
 [2.10201643e-02]
 [2.30414747e-03]
 [2.31073074e-01]
 [1.31665569e-02]
 [1.99677303e+02]
 [1.10436636e+02]
 [6.96402238e+01]
 [2.17865925e+01]
 [6.39749835e+01]
 [6.83067001e+01]]
db = 0.847926267281106
cost = nan


In [91]:
np.log(0)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


-inf

In [138]:
Z = np.matmul(w.T, X) + b    
                         # Z = [[z1, z2, ....]] = [[wtx1 + b, wtx2 + b, ....]]     ||      Z = [z1, z2, z3]
A = sigma(Z)  
for x in A:
    print(x)


[1. 1. 1. ... 1. 1. 1.]
